### ISSUE TITLE
Set up multi-stock PVA model

### ISSUE THREAD

**Issue by LewCoggins-NOAA** [LewCoggins-NOAA/GulfSturgeon#2]
Write code for the multi-stock model. Need to decide if it is best to just code from scratch or modify Bretts model

**Comment by LewCoggins-NOAA** [comment]
Decisions:
how general to make this simulation in terms of numbers of populations?
   Should probably just make 2 initially

Connectivity between populations?
   This is desirable in this particular application because these data are available and the Pearl in particular may not have net zero movement.

How much to rely on Bretts code versus recoding?
   Maybe just start with a stripped down version of Bretts code that does not include multiple simulation structure.

**Comment by LewCoggins-NOAA** [comment]
@sw-parker how many stocks should this model contain?

**Comment by sw-parker** [comment]
@LewCoggins-NOAA 2 for the west (Pearl and Pascagoula) and 3 for the central Gulf (Escambia, Yellow, and Choctawhatchee).

**Comment by LewCoggins-NOAA** [comment]
@sw-parker So that means 5 total, right?

**Comment by sw-parker** [comment]
@LewCoggins-NOAA If the multi-stock model is intended to represent dynamics for all stocks, there are 7 total populations

**Comment by LewCoggins-NOAA** [comment]
@sw-parker OK. I have the guts of a working version now (MetaPVA.R). I will continue with adding the extra buzzers and whistles tomorrow.

**Comment by LewCoggins-NOAA** [comment]
@sw-parker   
So I have now cleaned up the basic functionality to include episotic mortality events for juveniles and adults. I have some questions that I could use your help considering:

1) what ages should disperse from one stock to another?
2) what information should we retain for each simulation? I am currently returning the total abundance time series of each of the 5 populations. I am also returning the extirpation proportion.
3) What no fishing equilibrium population size should we specify for each population? 
4) What mortality rate should I consider as the baseline or best estimate?

Do you have time to look at this model tomorrow and provide input into these questions?

**Comment by sw-parker** [comment]
Annual adult mortality: 

Pearl: 1-0.76
Pascagoula: 1-0.87
Escambia: 1-0.87
Yellow: 1-0.87
Choc: 1-0.89
Apal: 1-0.89
Suwa: 1-0.89

**Comment by LewCoggins-NOAA** [comment]
@DanGwinn 

Hey Danno, can you make the rmultinom process to move fish between rivers any more efficient? This one command is making my code take 5x as long to run.

Have a look at this file. [MetaPVA2.R](https://github.com/LewCoggins-NOAA/GulfSturgeon/blob/main/MetaPVA2.R)

**Comment by LewCoggins-NOAA** [comment]
@sw-parker @billpine @DanGwinn 

With Ben Staton's help, I was able to incorporate parallel processing and speed up the execution a bunch. Also, I have been running the model on the NOAA supercomputer to run much faster. 



Still have to answer these questions:

what ages should disperse from one stock to another?
what information should we retain for each simulation? I am currently returning the total abundance and total adult time series of each of the 7 populations. I am also returning the extirpation probability of each river. 

Stephen also wants proportion of runs that decline from No to N@25years. I will probably compute the proportion of runs where the average adult abundance from N from years 20-25 have declined by 25% or more. Stephen, Let me know is that is not what you want.

Stephen, I will also compute the time series of average age and return that.

**Comment by LewCoggins-NOAA** [comment]
I closed this thread because it was redundant with the Overall extinction risk thread

@sw-parker @billpine @DanGwinn
